theme: jekyll-theme-chirpy
title: ðŸš† Railway Engineer 
description: Yiting Hsueh, a team-player with communication and language skills and passion in learning, observing and improving processes, successfully delivered several railway projects with high quality and customer satisfaction. Familiar to various railway onboard and wayside systems.
